language: node_js
node_js:
    - 13

branches:
    only:
        - master
		- develop
		- /^Release.*$/
        - /^Hotfix.*$/

cache:
    directories:
        - node_modules

before_install:
    - npm update
install:
    - npm install
script:
    - npm test
after_script:
    - npm run coveralls